AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  myVolume:
    Type: AWS::EC2::Volume
    DeletionPolicy: Snapshot
    Properties: 
      Size: 25
      Encrypted: true
      AvailabilityZone: !Select [1, !GetAZs ""]
      Tags:
        - Key: Name
          Value: Snap1