AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  VpcCidrRange:
    Type: String
    Description: CIDR range for the VPC
    Default: 10.0.0.0/16
  Subnet1CidrRange:
    Type: String
    Description: CIDR range for Subnet 1
    Default: 10.0.1.0/24
  Subnet2CidrRange:
    Type: String
    Description: CIDR range for Subnet 2
    Default: 10.0.2.0/24
  Subnet3CidrRange:
    Type: String
    Description: CIDR range for Subnet 3
    Default: 10.0.3.0/24
  VpcName:
    Type: String
    Description: Name of the VPC
Resources:
  BaseVPCStack:
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
          - W3002
      SamResourceId: BaseVPCStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-central-1.amazonaws.com/aws-sam-cli-managed-default-samclisourcebucket-47o5za40gagi/7283b856b76c793f17c95605eb4c6658.template
      Parameters:
        VpcCidrRange:
          Ref: VpcCidrRange
        Subnet1CidrRange:
          Ref: Subnet1CidrRange
        Subnet2CidrRange:
          Ref: Subnet2CidrRange
        Subnet3CidrRange:
          Ref: Subnet3CidrRange
        VpcName:
          Ref: VpcName
  EndpointsStack:
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
          - W3002
      SamResourceId: EndpointsStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-central-1.amazonaws.com/aws-sam-cli-managed-default-samclisourcebucket-47o5za40gagi/3e160dc2c88eff14f14286dc60ab83ab.template
      Parameters:
        VpcId:
          Fn::GetAtt:
          - BaseVPCStack
          - Outputs.VpcId
        SubnetIds:
          Fn::GetAtt:
          - BaseVPCStack
          - Outputs.SubnetIds
